version: '3.8'

services:
  slack-bot:
    build: .
    restart: unless-stopped
    environment:
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      HELP_CHANNEL: ${HELP_CHANNEL}
      TICKETS_CHANNEL: ${TICKETS_CHANNEL}
      AI_ENDPOINT: ${AI_ENDPOINT:-""}
      SLACK_WORKSPACE_DOMAIN: ${SLACK_WORKSPACE_DOMAIN:-"hackclub"}
      NODE_ENV: ${NODE_ENV:-production}
    volumes:
      - app-data:/app/data
      - ./lib:/app/lib:ro

volumes:
  app-data: